# Generated by Django 5.2.13 on 2026-04-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='template',
        ),
    ]
