# Generated by Django 5.2.13 on 2026-05-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_resume_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
