# Generated by Django 5.2.13 on 2026-05-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_education_field_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
