# Generated by Django 5.2.13 on 2026-05-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_resume_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
