# Generated by Django 5.2.13 on 2026-05-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_education_grade_education_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, choices=[('Languages', 'Languages'), ('Databases', 'Databases'), ('Tools', 'Tools'), ('Platforms', 'Platforms'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
