# Generated by Django 5.2.13 on 2026-05-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
    ]
